# Generated by Django 5.2.7 on 2025-10-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_studentapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
