# Generated by Django 5.2.7 on 2025-10-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_studentapplication_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='previous_grade_level',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='previous_grade_results',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
