# Generated by Django 5.2.7 on 2025-10-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_studentapplication_previous_grade_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
