# Generated by Django 5.2.7 on 2025-10-14 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_studentapplication_approved_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentapplication',
            name='approved_at',
        ),
        migrations.DeleteModel(
            name='StaffProfile',
        ),
    ]
