# Generated by Django 5.2.7 on 2026-02-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0007_staffprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="gallery_images/")),
                ("description", models.TextField(blank=True, null=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
