# Generated by Django 5.2.7 on 2026-02-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0008_galleryitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryitem",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="gallery/videos/"),
        ),
        migrations.AlterField(
            model_name="galleryitem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="gallery/images/"),
        ),
    ]
