# Generated by Django 5.2.7 on 2026-02-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0009_galleryitem_video_alter_galleryitem_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentLifeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="student_life/")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sport", "Sports Team"),
                            ("club", "Club or Society"),
                            ("boarding", "Boarding & Facilities"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
