# Generated by Django 5.2.7 on 2026-02-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0010_studentlifeitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadershipProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=100)),
                ("bio", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="staff_profiles/")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("admin", "Administration (Principal/Deputy)"),
                            ("teacher", "Teaching Staff"),
                            ("support", "Support Staff"),
                            ("prefect", "School Prefect"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="studentlifeitem",
            name="passport_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="staff_passports/"
            ),
        ),
    ]
