# Generated by Django 5.2.7 on 2026-02-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0011_leadershipprofile_studentlifeitem_passport_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadershipprofile",
            name="passport_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="staff_passports/"
            ),
        ),
    ]
