# Generated by Django 5.2.7 on 2025-10-16 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_mark_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mark',
        ),
    ]
